# Generated by Django 3.0.5 on 2020-07-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=80)),
                ('equipo', models.CharField(max_length=80)),
                ('posicion', models.CharField(choices=[('PORTERO', 'Portero'), ('DEFENSA', 'Defensa'), ('CENTROCAMPISTA', 'Centrocampista'), ('DELANTERO', 'Delantero')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('mi_equipo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField()),
                ('presupuesto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Liga')),
                ('pujador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(choices=[('SELECCIONADO', 'Seleccionado'), ('NO SELECCIONADO', 'No seleccionado')], max_length=30)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Jugador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Liga')),
            ],
        ),
        migrations.AddField(
            model_name='liga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Usuario'),
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada_sumada', models.CharField(choices=[('SI', 'SI'), ('NO', 'No')], max_length=30)),
                ('numero_jornada', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Jugador')),
            ],
        ),
    ]
