# Generated by Django 3.0.5 on 2020-07-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_de_inicio', models.IntegerField()),
                ('max_num_usuarios_liga', models.IntegerField()),
                ('num_jug_plant_inicio', models.IntegerField()),
                ('ultima_jornada', models.IntegerField()),
                ('sumar_puntos_jorn', models.CharField(choices=[('SI', 'SI'), ('NO', 'No')], max_length=30)),
            ],
        ),
    ]
