# Generated by Django 3.0.5 on 2020-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='seleccion',
            field=models.CharField(choices=[('SELECCIONADO', 'Seleccionado'), ('NO SELECCIONADO', 'No seleccionado')], max_length=30),
        ),
    ]
