# Generated by Django 3.0.1 on 2020-03-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nick',
            new_name='mi_equipo',
        ),
    ]
