# Generated by Django 3.0.5 on 2020-07-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puja',
            old_name='liga',
            new_name='liga_puja',
        ),
    ]
