# Generated by Django 3.0.5 on 2020-04-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0002_auto_20200428_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercado',
            old_name='jugador',
            new_name='jugador_mercado',
        ),
        migrations.RenameField(
            model_name='mercado',
            old_name='liga',
            new_name='liga_mercado',
        ),
    ]
