# Generated by Django 3.0.1 on 2020-03-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0002_auto_20200311_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=80)),
                ('equipo', models.CharField(max_length=80)),
                ('valor_mercado', models.IntegerField()),
                ('posicion', models.CharField(max_length=30)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
    ]
