# Generated by Django 3.0.5 on 2020-07-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0002_auto_20200709_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercado',
            old_name='fecha_increso',
            new_name='fecha_ingreso',
        ),
    ]
