# Generated by Django 3.0.1 on 2020-03-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0003_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('PORTERO', 'PORTERO'), ('DEFENSA', 'DEFENSA'), ('MEDIOCENTRO', 'MEDIOCENTRO'), ('DELANTERO', 'DELANTERO')], max_length=30),
        ),
    ]
