# Generated by Django 3.0.1 on 2020-03-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0004_auto_20200311_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('PORTERO', 'Portero'), ('DEFENSA', 'Defensa'), ('MEDIOCENTRO', 'Mediocentro'), ('DELANTERO', 'Delantero')], max_length=30),
        ),
        migrations.CreateModel(
            name='liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.usuario')),
            ],
        ),
    ]
