# Generated by Django 3.0.5 on 2020-04-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0004_auto_20200430_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='liga_mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Liga'),
        ),
    ]
