# Generated by Django 3.0.5 on 2020-05-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0005_auto_20200430_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Liga')),
                ('pujador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.Usuario')),
            ],
        ),
    ]
