# Generated by Django 3.0.1 on 2020-03-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0006_auto_20200321_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.liga')),
            ],
        ),
    ]
