# Generated by Django 3.0.5 on 2020-04-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0007_mercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.usuario', unique=True),
        ),
    ]
