# Generated by Django 3.0.5 on 2020-04-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0009_auto_20200412_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.usuario'),
        ),
    ]
