# Generated by Django 3.0.5 on 2020-04-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionApp', '0010_auto_20200419_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='username',
        ),
    ]
