# Generated by Django 3.0.5 on 2020-04-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=80)),
                ('equipo', models.CharField(max_length=80)),
                ('valor_mercado', models.IntegerField()),
                ('posicion', models.CharField(choices=[('PORTERO', 'Portero'), ('DEFENSA', 'Defensa'), ('MEDIOCENTRO', 'Mediocentro'), ('DELANTERO', 'Delantero')], max_length=30)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('mi_equipo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('puntuacion', models.IntegerField()),
                ('presupuesto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(choices=[('SELECCIONADO', 'Seleccionado'), ('NO_SELECCIONADO', 'No seleccionado')], max_length=30)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAplicacion.jugador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAplicacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAplicacion.jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAplicacion.liga')),
            ],
        ),
        migrations.AddField(
            model_name='liga',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAplicacion.usuario'),
        ),
    ]
