# Generated by Django 3.0.5 on 2020-04-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='valor_mercado',
        ),
    ]
